### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel plugins.voximplant.com/call_controller_events)

### ISSUE THREAD

**Issue by nerdsarena** [voximplant/flutter_callkit#20]
When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
<asynchronous suspension>

**Comment by YuliaGrigorieva** [comment]
Hello @nerdsarena,

Could you please provide some details how to reproduce and the following information:
- flutter version
- flutter_callkit_voximplant version
- ios version?

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
hello @nerdsarena ,

Thank you for information provided.

We wil check if we can reproduce the issue with an android app and will get back to you soon.

Regarding the issue with audio on iOS, it does not seem to be related to this error. Please check if you use FCXProviderDidActivateAudioSession/FCXProviderDidDeactivateAudioSession events in your project.

https://github.com/voximplant/flutter_callkit/blob/09b666e461135ca0fe271e668b5ac74b4c8de713/lib/src/provider.dart#L88-L98

The audio in a call should start only after CallKit activates the audio session, otherwise there might be issues to get the audio from the microphone or play audio to an audio device (speaker, receiver, headset).

Best regards,
Yulia Grigorieva

**Comment by nerdsarena** [comment]
after investigation we found issue that audio session not active when response from background
after a lot of search we understand that audio session activated from callkit it self but this not happen in our case
can you help us with any sample code how to activate audio session when it's not activated
thanks

similar issue 
https://developer.apple.com/forums/thread/64544
https://github.com/AgoraIO/Advanced-Video/issues/135
https://stackoverflow.com/questions/54007207/audio-seems-not-work-with-callkit-when-incoming-call-is-answered
